### ISSUE TITLE
about core_rnn_cell._linear

### ISSUE THREAD

**Issue by LeslieZhoa** [MWransky/dialogue-gan#2]
Thank you for your share.
The version of my tensorflow is 1.4.0, and there is not core_rnn.linear.
I repalce it with the code below and it works.

from tensorflow.python.ops import rnn_cell_impl
linear=rnn_cell_impl._linear

Wait for your answer.

**Comment by MWransky** [comment]
Hi there! Yes, you are correct in that tensorflow changed that aspect of its API. I've updated the `gen/seq2seq.py` file to account for this.

Thank you for bringing it to my attention!
